# Generated by Django 5.2.5 on 2026-05-23 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('carbon_multiplier', models.FloatField(default=0.0, verbose_name='CO2 Saved per KG')),
                ('points_multiplier', models.IntegerField(default=0, verbose_name='Points per KG')),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_weight', models.FloatField(verbose_name='Estimated Weight (KG)')),
                ('actual_weight', models.FloatField(blank=True, null=True, verbose_name='Actual Weight (Recycler Verified in KG)')),
                ('pickup_address', models.TextField(verbose_name='Pickup Address/Notes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recycler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_pickups', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Recycler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL, verbose_name='Normal User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.wastecategory', verbose_name='Waste Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
